name: moniepoint_test
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router:
  get_it:
  provider:
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mocktail:
  build_runner:
  flutter_gen_runner:
  freezed_annotation: 
  freezed:

flutter_gen:
  output: lib/common/gen/
  integrations:
    flutter_svg: true
  # assets:
  #   enabled: true
  #   outputs:
  #     class_name: AccelerateAssets
  #     package_parameter_enabled: false
  fonts:
    outputs:
      class_name: AppFonts
      package_parameter_enabled: true
  # colors:
  #   class_name: AccelerateColors
  #   inputs:
  #     - assets/color/colors.xml

flutter:
  uses-material-design: true
  fonts:
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Bold.ttf
          weight: 700
        - asset: assets/fonts/SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Medium.ttf
          weight: 500
        - asset: assets/fonts/Regular.ttf
          weight: 400
        - asset: assets/fonts/Light.ttf
          weight: 300
        - asset: assets/fonts/ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/ExtraLight.ttf
          weight: 100
